config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect, render
from django.http import Http404
from django.conf import settings
from django.contrib.auth.decorators import login_required


def router(request):
    user = request.user

    if not user.is_authenticated:
        return redirect("account:login-or-register")
    
    if user.is_superuser or user.is_staff:
        return redirect("admin:index")
    elif user.is_team_member and user.user_of_road_registration.first():
        registration_obj = user.user_of_road_registration.first()
        if registration_obj.status != "n":
            return redirect("content:roads")
        if int(registration_obj.status_user_state) == 2:
            return redirect("account:register2")
        elif int(registration_obj.status_user_state) == 3:
            return redirect("account:register3")
        elif int(registration_obj.status_user_state) == 4:
            return redirect("account:register4")
        elif int(registration_obj.status_user_state) == 5:
            return redirect("account:user-dashboard")
        return redirect("content:roads")
    elif user.is_center_staff():
        return redirect("company:acc-dashboard")
    elif user.is_referee:
        return redirect("account:referee-dashboard")
    elif user.is_mentor:
        return redirect("account:mentor-dashboard")
    elif user.is_investor:
        return redirect("investor:dashboard")
    elif user.is_company:
        return redirect("company:dashboard")
    else:
        raise Http404("You do not have valid permissions!")


@login_required
def under_maintenance(request):
    return render(request, "under_maintenance.html", {})


@login_required
def forbidden(request, *args, **kwargs):
    return render(request, "forbidden.html", {})


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", router, name="router"),
    path("under-maintenance", under_maintenance, name="under-maintenance"),
    path('accounts/', include('account.urls')),
    path('content/', include('content.urls')),
    path('company/', include('company.urls')),
    path('quiz/', include('quiz.urls')),
    path('plan/', include('plan.urls')),
    path('team/', include('team.urls')),
    path('investor/', include('investor.urls')),
    path('assessment/', include('assessment.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/urls.py
from django.urls import path
from . import views
from config.urls import forbidden

app_name = "plan"
urlpatterns = [
    path("create/", views.CreatePlan.as_view(), name="create"),
    path("<str:uuid>/profile/", views.TeamProductProfile.as_view(), name="profile"),
    path("<str:uuid>/detail/", views.PlanDetail.as_view(), name="detail"),
]

quiz/urls.py
from django.urls import path
from . import views

app_name = "quiz"
urlpatterns = [
    path("<str:exam_uuid>-<str:collection_uuid>/exam/", views.ExamDetail.as_view(), name="exam-detail"),

    # ========= PreRegister Tasks and Tests:
    path("pre-register-required/<str:road_uuid>/", views.PreRegisterRequired.as_view(), name="pre-register-required"),
    path("pre-register-required-team/<str:road_uuid>/", views.PreRegisterRequiredTeam.as_view(), name="pre-register-required-team"),
    path("pre-register-required-individual/<str:road_uuid>/", views.PreRegisterRequiredIndividual.as_view(), name="pre-register-required-individual"),
    path("task-response-detail/<str:user_uuid>/", views.PreRegisterTaskResponseDetail.as_view(), name="task-response-detail"),

    path("iam-individual/<str:uuid>/", views.i_am_team_individual, name="iam-individual"),
    path("iam-tmember/<str:uuid>/", views.i_am_team_member, name="iam-tmember"),
    path("iam-coordinator/<str:uuid>/", views.i_am_team_coordinator, name="iam-coordinator"),

    path("personal-tests/<str:road_uuid>/", views.PreRegisterPersonalTests.as_view(), name="pre-register-personal-tests"),
    path("personal-tests-result/<str:user_uuid>/", views.PersonalTestsResult.as_view(), name="personal-tests-result"),
    path("pre-register-challenge/<str:road_uuid>/", views.PreRegisterChallenges.as_view(), name="pre-register-challenge"),
    path("save_task_question_response/<str:task_uuid>/<str:road_uuid>/", views.save_task_question_response, name="save_task_question_response"),
    path("pre-register-challenge-update/<str:task_res_uuid>/<str:road_uuid>/", views.PreRegisterChallengesUpdate.as_view(), name="pre-register-challenge-update"),
]

team/urls.py
from django.urls import path
from . import views

app_name = "team"
urlpatterns = [
    path("", views.TeamDashboard.as_view(), name="dashboard"),
    path("<str:uuid>/profile/", views.TeamProfile.as_view(), name="profile"),
    path("manage-teams/", views.CreateTeam.as_view(), name="manage-teams"),
    path("<str:uuid>/update-team/", views.UpdateTeam.as_view(), name="update-team"),
    path("save-team-member/", views.save_team_member, name="save-team-member"),
    path("<str:uuid>/<str:team_uuid>/delete-team-member/", views.delete_team_member, name="delete-team-member"),
    path("road-registration/<str:uuid>/", views.RoadRegistrationView.as_view(), name="road-registration"),
    path("registration/detail/<str:uuid>/", views.RegistrationDetail.as_view(), name="registration-detail"),
    path("reject_registration/<str:uuid>/", views.reject_registration, name="reject_registration"),
    path("approve_registration/<str:uuid>/", views.approve_registration, name="approve_registration"),
    path("funds/management/", views.FundsManagements.as_view(), name="funds-management"),
    path("idea/management/", views.IdeaManagements.as_view(), name="idea-management"),
    path("product/management/", views.ProductManagements.as_view(), name="product-management"),
    path("save/product/", views.save_product, name="save-product"),
    path("save-extra-day-for-complete-registration/", views.save_extra_day_for_complete_registration, name="save-extra-day-for-complete-registration"),
    path("product/<str:user_uuid>/profile/", views.PlanAndTeamProfile.as_view(), name="plan-team-profile"),
    path("add/product/", views.AddProduct.as_view(), name="add-product"),
    path("searchZi/", views.searchzi, name="searchZi"),
    path("search/", views.search_iframe, name="search-iframe"),

    path('logoutt/', views.create_team, name='create_center'),
]

team/models.py
from typing import Union
from django.db import models
from django.db.models import Q
from datetime import date
from utils.uuid_generator import random_uuid4
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


def validate_numeric(value):
    if not value.isdigit():
        raise ValidationError(
            _('کدملی باید شامل اعداد باشد.'),
            params={'value': value},
        )


class Category(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    
    name = models.CharField(verbose_name="نام", max_length=255)

    created_time = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

    def __str__(self) -> str:
        return self.name


class StartUpTeam(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    
    name = models.CharField(verbose_name="نام تیم", max_length=255)
    STATUS = (
        ("a", "فعال"), # Active
        ("i", "غیر فعال"), # Inactive
    )
    status = models.CharField(choices=STATUS, max_length=1, default="a", verbose_name="وضعیت", null=True, blank=True)
    description = models.TextField(verbose_name="بیوگرافی تیم")
    category = models.CharField(verbose_name="دسته بندی زمینه فعالیت", max_length=255)

    created_time = models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, verbose_name="زمان آخرین بروزرسانی")

    class Meta:
        verbose_name = "تیم"
        verbose_name_plural = "تیم ها"

    def __str__(self) -> str:
        return self.name
    
    def team_member_count(self) -> int:
        return self.team_of_team_member.count()
    team_member_count.short_description = "تعداد اعضا"
    
    def all_users_completed_registration(self) -> bool:
        team_member_objects = self.team_of_team_member.all()
        team_member_count = team_member_objects.count() - 1
        coordinator_completion_status = None

        if team_member_count < 1:
            return False

        for member in team_member_objects:
            member_register_object = member.user.user_of_road_registration.first()

            if member_register_object.team != self:
                continue

            if member.is_owner:
                coordinator_completion_status = member_register_object.is_complete_registration_for_coordinator()
                continue

            if member_register_object.is_complete_registration_for_team_member():
                team_member_count -= 1

        if team_member_count == 0:
            team_member_count = True
        else:
            team_member_count = False

        return team_member_count and coordinator_completion_status
    
    
def search_items(query:str):
    qs = query.split(",")
    
    # Filter Category objects
    # categories = Category.objects.filter(
    #     Q(name__icontains=query)
    # )

    # Filter StartUpTeam objects
    result = None
    
    for q in qs:
        if result is None:
            result = StartUpTeam.objects.filter(
                Q(name__icontains=q) |
                Q(description__icontains=q) |
                Q(category__name__icontains=q)
            )
        else:
            tmp = StartUpTeam.objects.filter(
                Q(name__icontains=q) |
                Q(description__icontains=q) |
                Q(category__name__icontains=q)
            )
            result | tmp

    unique_result = result.distinct()

    return unique_result


class TeamMember(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    
    team = models.ForeignKey(StartUpTeam, verbose_name="تیم", on_delete=models.CASCADE, related_name="team_of_team_member")
    user = models.ForeignKey("account.User", verbose_name="عضو", on_delete=models.CASCADE, related_name="user_of_team_member", null=True, blank=True)
    is_coordinator = models.BooleanField(verbose_name="هماهنگ کننده؟", default=False)
    is_owner = models.BooleanField(verbose_name="سازنده این تیم؟", default=False)

    created_time = models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, verbose_name="زمان آخرین بروزرسانی")

    class Meta:
        verbose_name = "عضو تیم"
        verbose_name_plural = "عضو های تیم"

    def __str__(self) -> str:
        return f"{self.user.get_full_name()} از تیم {self.team.name}"


class RoadRegistration(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    team = models.ForeignKey(StartUpTeam, related_name="team_of_road_registration", verbose_name="تیم", on_delete=models.CASCADE, null=True, blank=True)
    team_name = models.CharField(verbose_name="نام تیم", max_length=255, null=True, blank=True)
    user = models.ForeignKey("account.User", related_name="user_of_road_registration", verbose_name="کاربر", on_delete=models.CASCADE)
    road = models.ForeignKey("content.Road", related_name="road_of_road_registration", verbose_name="مسیر", on_delete=models.CASCADE)

    STATUS = (
        ("n", "شما نیاز به تکمیل فرایند ثبت‌نام خود دارید"), # Need to complete the profile
        ("w", "درخواست شما توسط برگزار کننده هنوز بررسی نشده است"), # Waiting
        ("p", "درخواست شما در حال بررسی توسط برگزارکننده می‌باشد"), # Progressing
        ("a", "پذیرش شما در برنامه تایید شده است"), # Approved
        ("r", "درخواست شما رد شده"), # Reject
        ("c", "شما برای تکمیل فرایند ثبت‌نام نیاز به اصلاح درخواست و اطلاعات خود دارید"), # Correction
    )
    status = models.CharField(verbose_name="وضعیت", max_length=1, default="n", choices=STATUS)

    client_last_response_date = models.DateField("زمان آخرین تغییر توسط کاربر", auto_now=False, auto_now_add=False, null=True, blank=True)
    accelerator_last_response_date = models.DateField("زمان آخرین واکنش توسط شتابدهنده", auto_now=False, auto_now_add=False, null=True, blank=True)

    TEAM_OR_INDIVIDUAL = (
        ("t", "تیم"),
        ("i", "فرد"),
        ("a", "تیم (اضافه شده توسط هماهنگ کننده)"),
    )
    team_or_individual = models.CharField(verbose_name="تیم یا فرد؟", max_length=1, default="t", choices=TEAM_OR_INDIVIDUAL)
    STATUS_USER_STATE = (
        ("2", "مرحله دوم تکمیل ثبت نام"),
        ("3", "مرحله سوم تکمیل ثبت نام"),
        ("4", "مرحله چهارم تکمیل ثبت نام"),
        ("5", "ثبت نام کامل"),
    )
    status_user_state = models.CharField(verbose_name="وضعیت ثبت نام کاربر", max_length=2, default="2", choices=STATUS_USER_STATE)

    # validity_pride_days = validity_period_days
    # for all process in user request
    validity_pride_days = models.PositiveIntegerField(verbose_name="مهلت تکمیل درخواست (به روز)", default=10)
    # for complete the challenge
    validity_pride_days_for_challenge = models.PositiveIntegerField(verbose_name="مهلت تکمیل چالش (به روز)", default=3)
    complete_registration_date = models.DateField("تاریخ تکمیل اطلاعات توسط کاربر", auto_now=False, auto_now_add=False, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, verbose_name="زمان آخرین بروزرسانی")

    class Meta:
        verbose_name = "ثبت نام مسیر آموزشی"
        verbose_name_plural = "ثبت نام مسیرهای آموزشی"

    def __str__(self) -> str:
        return f"{self.user.get_full_name()} - مسیر {self.road.name}"
    
    def is_valid_registration_period(self):
        """_summary_

        Returns:
            False (boolean): It will be returned if the user registration is not complete.
            'True' (string): It mean user complete the registration.
            __int__ : It show the days passed from the registration date. This is obtained by subtracting the user's registration completion date from today's date.
        """
        
        try: # If registration for a team
            team_owner = self.team.team_of_team_member.filter(is_owner=True).first().user
            
            if team_owner.user_of_road_registration.first().client_last_response_date:
                return "True"
            
            team_owner_complete_registration_date = team_owner.user_of_road_registration.first().complete_registration_date
            team_owner_validity_pride_days = team_owner.user_of_road_registration.first().validity_pride_days

            if team_owner_complete_registration_date is None:
                return False 

            days_passed = (date.today() - team_owner_complete_registration_date).days
            return team_owner_validity_pride_days - days_passed
        except: # If registration for an individual
            if self.client_last_response_date:
                return "True"
            
            if self.complete_registration_date is None:
                return False  # or True depending on your requirement when there's no start date

            days_passed = (date.today() - self.complete_registration_date).days
            return self.validity_pride_days - days_passed

    def is_valid_registration_period_for_challenge(self):
        """_summary_

        Returns:
            False (boolean): It will be returned if the user registration is not complete.
            'True' (string): It mean user complete the registration.
            __int__ : It show the days passed from the registration date. This is obtained by subtracting the user's registration completion date from today's date.
        """
        
        if self.client_last_response_date:

templates/team/road-registration.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load tag_library %}

{% block page_css %}
<link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/vendors/css/forms/select/select2.min.css" %}>
<link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/css-rtl/pages/faq.css" %}>
{% endblock page_css %}

{% block main %}
<div class="row">

    {% include "elements/messages-section.html" %}

    <div class="col-12 card">
        <div class="row">
            <div class="col-lg-8 p-0">
                <img src="{% if object.poster %}{{object.poster.url}}{% else %}{% static "no-banner.jpg" %}{% endif %}" alt="{{object.name}}" class="img-fluid">
            </div>
            <div class="col-lg-4">
                <div class="h-100 p-2">
                    <h2 class="mt-3 mr-3 font-weight-bold">{{object.name}}</h2>
                    <li class="list-group mt-2">
                        <i class="text-black-50 mt-50"><i class="feather icon-tag"></i> هزینه: <span class="{% if object.price <= 0 %}text-warning{% endif %}">{{object.price|not_zero}}</span></i>
                        <i class="text-black-50 mt-50"><i class="feather icon-map-pin"></i> محل برگزاری: {{object.location}}</i>
                        <i class="text-black-50 mt-50">برگزار کننده: <img src={% if object.accelerator.logo %}{{object.accelerator.logo.url}}{% else %}{% static "no-banner.jpg" %}{% endif %} alt={{object.accelerator.name}} class="img-thumbnail" width="100"></i>
                    </li>

                    {% if is_register and is_register.status_user_state in "fm" %}
                        {% if is_register.status == "w" %}
                        <span class="btn btn-block btn-gradient-bg bg-gradient-info mt-3">وضعیت: <b>{{is_register.get_status_display}}</b></span>
                        {% elif is_register.status == "p" %}
                        <span class="btn btn-block btn-gradient-bg bg-gradient-warning mt-3">وضعیت: <b>{{is_register.get_status_display}}</b></span>
                        {% elif is_register.status == "d" %}
                        <span class="btn btn-block btn-gradient-bg bg-gradient-success mt-3">وضعیت: <b>{{is_register.get_status_display}}</b></span>
                        {% elif is_register.status == "r" %}
                        <span class="btn btn-block btn-gradient-bg bg-gradient-danger mt-3">وضعیت: <b>{{is_register.get_status_display}}</b></span>
                        {% endif %}
                    {% else %}
                    <a href="{% url "quiz:pre-register-required" object.pre_register_task.uuid object.uuid %}" class="btn btn-block btn-gradient-bg bg-gradient-success mt-3">ثبت درخواست</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


    <div class="col-12">
        <div class="row">
            <div class="col-lg-8">
                <!-- Detail and registration button -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">ثبت درخواست شرکت در این برنامه</h4>
                    </div>
                    <div class="card-body">
                        <div class="card-content">
                            <table class="table table-responsive-md mb-0 text-dark">
                                <thead>
                                    <tr class="table-light">
                                        <th scope="col">توضیحات</th>
                                        <th scope="col">تعداد فصل ها</th>
                                        <th scope="col">تعداد گام ها</th>
                                        <th scope="col">تعداد مربی ها</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="col-6 text-justify">{{object.description}}</td>
                                        <td class="">{{object.accelerator.accelerator_of_collection.count}} <span class="text-black-50">فصل</span></td>
                                        <td class="">{{object.accelerator.accelerator_of_content.count}} <span class="text-black-50">گام</span></td>
                                        <td class="">{{object.accelerator.mentors.count}} <span class="text-black-50">مربی</span></td>
                                    </tr>
                                </tbody>
                            </table>

                            {% comment %}
                            <form method="post" class="mt-2" action={% url "team:road-registration" object.uuid %}>
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    <select class="form-control" name="register_type">
                                        <option value="0">شخصی (درخواست فعال شدن برنامه فقط برای خود شما)</option>
                                        {% for team in request.user.members_of_team.all %}
                                        <option value="{{team.uuid}}">{{team.name}}</option>
                                        {% endfor %}
                                    </select>
                                </fieldset>
                                <button type="submit" class="btn btn-block btn-gradient-bg bg-gradient-success">ثبت درخواست</button>
                            </form>
                            {% endcomment %}
                        </div>
                    </div>
                </div>
                <!-- FAQ -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"><i class="fa fa-question-circle"></i> سوالات متداول</h4>
                    </div>
                    <div class="card-body">
                        <div class="card-content">
                            <div class="accordion search-content-info" id="accordionExample">
                                <div class="collapse-margin search-content mt-0">
                                    <div class="card-header" id="headingOne" role="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        <span class="lead collapse-title">میشه گام ها و مراحل برنامه به صورت آنلاین هم طی کرد؟</span>
                                    </div>
                                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                                        <div class="card-body">
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                        </div>
                                    </div>
                                </div>
                                <div class="collapse-margin">
                                    <div class="card-header" id="headingTwo" role="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        <span class="lead collapse-title collapsed">
                                            گام ها و آزمون های دیجی نکست دارای مدال هستند؟
                                        </span>
                                    </div>
                                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                                        <div class="card-body">
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                        </div>
                                    </div>
                                </div>
                                <div class="collapse-margin search-content">
                                    <div class="card-header" id="headingThree" role="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                        <span class="lead collapse-title collapsed">
                                            چجوری به دریافت سرمایه برسم؟
                                        </span>
                                    </div>
                                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                                        <div class="card-body">
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- About accelerator -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"><i class="fa fa-question-circle"></i> برگزار کننده این برنامه:</h4>
                    </div>
                    <div class="card-body pb-1">
                        <div class="card-content text-dark">
                            <ul class="list-inline row justify-content-center">
                                <li><img src={% if object.accelerator.logo %}{{object.accelerator.logo.url}}{% else %}{% static "no-banner.jpg" %}{% endif %} alt={{object.accelerator.name}} class="img-thumbnail" width="100"></li>
                                <li class="ml-2">{{object.accelerator.name}}</li>
                                <li class="ml-2"><span class="badge badge-danger">{{object.accelerator.get_type_display}}</span></li>
                            </ul>

                            <p class="mt-3">{{object.accelerator.short_description}}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="card-content">
                            <li class="list-group">
                                <i class=""><i class="fa fa-circle-o"></i> شروع: {{object.start_date|to_jalali}}</i>
                                <i class="mt-25"><i class="fa fa-circle-o"></i> پایان: {{object.start_date|to_jalali}}</i>
                                <i class="mt-25"><i class="fa fa-circle-o"></i> مهلت ثبت نام تا: {{object.start_date|to_jalali}}</i>
                                <i class="mt-25"><i class="fa fa-circle-o"></i> شروع برنامه: {{object.start_date|to_jalali}}</i>
                            </li>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock main %}

{% block page_js %}
<script src={% static "admin-theme/app-assets/vendors/js/forms/select/select2.full.min.js" %}></script>
<script src={% static "admin-theme/app-assets/js/scripts/forms/select/form-select2.js" %}></script>
<script src={% static "admin-theme/app-assets/js/scripts/pages/faq-kb.js" %}></script>
{% endblock page_js %}

templates/team/search-iframe.html
{% extends "base.html" %}

{% load static %}
{% load tag_library %}

{% block page_css %}{% endblock page_css %}

{% block main %}
<div class="row">

    <div class="col-12">
        <iframe src="{% url "team:searchZi" %}" frameborder="0" width="100%" height="750"></iframe>
    </div>

</div>
{% endblock main %}

{% block page_js %}{% endblock page_js %}

templates/team/searchZi.html
{% load static %}

<html lang="fa" dir="rtl">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="author" content="colorlib.com">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800" rel="stylesheet" />
    <link href={% static "searchZi/css/main.css" %} rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/css-rtl/bootstrap.css" %}>
  </head>
  <body>

    <div class="s004">
      <form method="GET" action="{% url 'team:searchZi' %}">
        <fieldset>
          <legend class="text-dark">BoxZi Search: جستجوگر پلتفرم</legend>
          <div class="inner-form">
            <div class="input-field">
              <input class="form-control" name="q" id="choices-text-preset-values" type="text" placeholder="جستجو کنید..." />
              <button class="btn-search" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                  <path d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"></path>
                </svg>
              </button>
            </div>
          </div>
          {% comment %} <div class="suggestion-wrap">
            <span class="text-dark">Ladies</span>
            <span class="text-dark">Mens</span>
            <span class="text-dark">Accessories</span>
            <span class="text-dark">Sale</span>
          </div> {% endcomment %}

          {% if result %}
          <div class="mt-5">
            <hr>
            <h2 class="text-center">نتایج جستجو شما <small class="text-black-50">({{result.count}})</small></h2>
            <table class="table table-striped">
              <thead>
                <tr class="">
                  <th scope="col">نام</th>
                  <th scope="col">توضیحات</th>
                  <th scope="col">دسته بندی</th>
                </tr>
              </thead>
              <tbody>
                {% for item in result %}
                <tr>
                  <td class="font-weight-bold">{{item.name}}</td>
                  <td>{{item.description}}</td>
                  <td>{{item.category.name}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          {% endif %}

        </fieldset>
      </form>
    </div>

    <script src={% static "searchZi/js/extention/choices.js" %}></script>
    <script>
      var textPresetVal = new Choices('#choices-text-preset-values',
      {
        removeItemButton: true,
      });

    </script>
  </body>
</html>