config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect, render
from django.http import Http404
from django.conf import settings
from django.contrib.auth.decorators import login_required


def router(request):
    user = request.user

    if not user.is_authenticated:
        return redirect("account:login-or-register")
    
    if user.is_superuser or user.is_staff:
        return redirect("admin:index")
    elif user.is_team_member and user.user_of_road_registration.first():
        registration_obj = user.user_of_road_registration.first()
        if registration_obj.status != "n":
            return redirect("content:roads")
        if int(registration_obj.status_user_state) == 2:
            return redirect("account:register2")
        elif int(registration_obj.status_user_state) == 3:
            return redirect("account:register3")
        elif int(registration_obj.status_user_state) == 4:
            return redirect("account:register4")
        elif int(registration_obj.status_user_state) == 5:
            return redirect("account:user-dashboard")
        return redirect("content:roads")
    elif user.is_center_staff():
        return redirect("company:acc-dashboard")
    elif user.is_referee:
        return redirect("account:referee-dashboard")
    elif user.is_mentor:
        return redirect("account:mentor-dashboard")
    elif user.is_investor:
        return redirect("investor:dashboard")
    elif user.is_company:
        return redirect("company:dashboard")
    else:
        raise Http404("You do not have valid permissions!")


@login_required
def under_maintenance(request):
    return render(request, "under_maintenance.html", {})


@login_required
def forbidden(request, *args, **kwargs):
    return render(request, "forbidden.html", {})


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", router, name="router"),
    path("under-maintenance", under_maintenance, name="under-maintenance"),
    path('accounts/', include('account.urls')),
    path('content/', include('content.urls')),
    path('company/', include('company.urls')),
    path('quiz/', include('quiz.urls')),
    path('plan/', include('plan.urls')),
    path('team/', include('team.urls')),
    path('investor/', include('investor.urls')),
    path('assessment/', include('assessment.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from . import views

app_name = "content"
urlpatterns = [
    path("roads/", views.Roads.as_view(), name="roads"),
    path("road-detail/<str:uuid>/", views.RoadDetail.as_view(), name="road-detail"),
    path("<str:uuid>/detail/", views.ContentDetail.as_view(), name="detail"),
    path("watched-content/<str:content_uuid>", views.user_watched_content, name="watched-content"),
    path("funds/management/", views.FundsManagements.as_view(), name="funds-management"),
]

plan/urls.py
from django.urls import path
from . import views
from config.urls import forbidden

app_name = "plan"
urlpatterns = [
    path("create/", views.CreatePlan.as_view(), name="create"),
    path("<str:uuid>/profile/", views.TeamProductProfile.as_view(), name="profile"),
    path("<str:uuid>/detail/", views.PlanDetail.as_view(), name="detail"),
]

quiz/urls.py
from django.urls import path
from . import views

app_name = "quiz"
urlpatterns = [
    path("<str:exam_uuid>-<str:collection_uuid>/exam/", views.ExamDetail.as_view(), name="exam-detail"),

    # ========= PreRegister Tasks and Tests:
    path("pre-register-required/<str:road_uuid>/", views.PreRegisterRequired.as_view(), name="pre-register-required"),
    path("pre-register-required-team/<str:road_uuid>/", views.PreRegisterRequiredTeam.as_view(), name="pre-register-required-team"),
    path("pre-register-required-individual/<str:road_uuid>/", views.PreRegisterRequiredIndividual.as_view(), name="pre-register-required-individual"),
    path("task-response-detail/<str:user_uuid>/", views.PreRegisterTaskResponseDetail.as_view(), name="task-response-detail"),

    path("iam-individual/<str:uuid>/", views.i_am_team_individual, name="iam-individual"),
    path("iam-tmember/<str:uuid>/", views.i_am_team_member, name="iam-tmember"),
    path("iam-coordinator/<str:uuid>/", views.i_am_team_coordinator, name="iam-coordinator"),

    path("personal-tests/<str:road_uuid>/", views.PreRegisterPersonalTests.as_view(), name="pre-register-personal-tests"),
    path("personal-tests-result/<str:user_uuid>/", views.PersonalTestsResult.as_view(), name="personal-tests-result"),
    path("pre-register-challenge/<str:road_uuid>/", views.PreRegisterChallenges.as_view(), name="pre-register-challenge"),
    path("save_task_question_response/<str:task_uuid>/<str:road_uuid>/", views.save_task_question_response, name="save_task_question_response"),
    path("pre-register-challenge-update/<str:task_res_uuid>/<str:road_uuid>/", views.PreRegisterChallengesUpdate.as_view(), name="pre-register-challenge-update"),
]

content/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField
from django_quill.forms import QuillFormField
from quiz.models import Exam

from .models import Road, Collection, Content, CollectionOrder, ContentOrder


class RoadCreateForm(ModelForm):
    class Meta:
        model = Road
        exclude = ("created_time", "last_update_time", "uuid")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.fields[field_name].required = True
            if isinstance(field, ModelMultipleChoiceField):
                field.widget.attrs['class'] = 'select2'
        self.fields["poster"].widget.attrs['class'] = "form-control"
        self.fields["start_date"].widget.attrs['class'] = "flatpickr-date"
        self.fields["expiration_date"].widget.attrs['class'] = "flatpickr-date"
        self.fields["publish_date"].widget.attrs['class'] = "flatpickr-date"
        self.fields["registration_deadline"].widget.attrs['class'] = "flatpickr-date"


class RoadUpdateForm(ModelForm):
    class Meta:
        model = Road
        exclude = ("created_time", "last_update_time", "uuid", "accelerator")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            self.fields[field_name].required = True
            if isinstance(field, ModelMultipleChoiceField):
                field.widget.attrs['class'] = 'select2'
        self.fields["poster"].widget.attrs['class'] = "form-control"
        self.fields["start_date"].widget.attrs['class'] = "flatpickr-date"
        self.fields["expiration_date"].widget.attrs['class'] = "flatpickr-date"
        self.fields["publish_date"].widget.attrs['class'] = "flatpickr-date"
        self.fields["registration_deadline"].widget.attrs['class'] = "flatpickr-date"


class CollectionCreateForm(ModelForm):
    class Meta:
        model = Collection
        exclude = ("created_time", "last_update_time", "type", "uuid", "exam")

    def __init__(self, *args, **kwargs):
        super(CollectionCreateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, ModelMultipleChoiceField):
                field.widget.attrs['class'] = 'select2'


class CollectionOrderCreateForm(ModelForm):
    class Meta:
        model = CollectionOrder
        exclude = ("created_time", "last_update_time")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(CollectionOrderCreateForm, self).__init__(*args, **kwargs)
        self.fields['collection'].queryset = Collection.objects.filter(accelerator=user.access_to_center)


class CollectionUpdateForm(ModelForm):
    class Meta:
        model = Collection
        exclude = ("created_time", "last_update_time", "type", "uuid", "accelerator", "exam")

    def __init__(self, *args, **kwargs):
        super(CollectionUpdateForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, ModelMultipleChoiceField):
                field.widget.attrs['class'] = 'select2'


class ContentCreateForm(ModelForm):
    class Meta:
        model = Content
        content = QuillFormField()
        exclude = ("created_time", "last_update_time", "uuid")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, ModelMultipleChoiceField):
                field.widget.attrs['class'] = 'select2'


class ContentUpdateForm(ContentCreateForm):
    class Meta:
        model = Content
        exclude = ("created_time", "last_update_time", "uuid", "accelerator")


class ContentOrderCreateForm(ModelForm):
    class Meta:
        model = ContentOrder
        exclude = ("created_time", "last_update_time")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(ContentOrderCreateForm, self).__init__(*args, **kwargs)
        self.fields['content'].queryset = Content.objects.filter(accelerator=user.access_to_center)

content/views.py
import logging
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, View, ListView
from itertools import chain
from team.models import RoadRegistration

from .models import Content, WatchedContent, Road

logging.basicConfig(level=logging.ERROR, format='%(asctime)s - %(levelname)s - %(message)s')

class Roads(LoginRequiredMixin, View):
    template_name = "content/roads.html"
    context = {"title":"مسیرآموزشی"}

    def get(self, request):
        user = request.user
        registration_obj = user.user_of_road_registration.first()
        if not registration_obj.status_user_state == "5":
            return redirect("router")
        
        try:
            road = registration_obj.road
        except:
            road = Road.objects.first()

        task = road.pre_register_task
        task_business_side = road.pre_register_task_for_business_side

        count_of_t_question = task.pre_register_of_pre_register_task_question.count()
        count_of_b_question = task_business_side.pre_register_of_pre_register_task_question.count()
        user_response_count = user.user_of_pre_register_task_response.count()

        if user.user_of_road_registration.first().team_or_individual == "i":
            if user.type == "t":
                if (count_of_t_question - user_response_count) < 1:
                    self.context["challenge_response"] = True
                else:
                    self.context["challenge_response"] = False
            elif user.type == "b":
                if (count_of_b_question - user_response_count) < 1:
                    self.context["challenge_response"] = True
                else:
                    self.context["challenge_response"] = False

        self.context["object"] = Road.objects.first()
        self.context["registration_obj"] = request.user.user_of_road_registration.first()
        return render(request, self.template_name, self.context)
    

class RoadDetail(LoginRequiredMixin, DetailView):
    model = Road
    template_name = "content/road.html"
    slug_field, slug_url_kwarg = "uuid", "uuid"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "مسیر آموزشی"
        context["watched_list"] = WatchedContent.objects.filter(user=self.request.user).values_list('content__uuid', flat=True)

        collections = self.get_object().road_of_collection_order.all()
        steps = []
        for col_ord in collections:
            contents = col_ord.collection.collection_of_content_order.all()
            exams = col_ord.collection.collection_of_exam_order.all()
            tasks = col_ord.collection.collection_of_task_order.all()
            collection_steps = sorted(chain(contents, exams, tasks), key=lambda x: x.row_number)
            steps.extend(collection_steps)
        context["collections"] = collections
        context["steps"] = sorted(steps, key=lambda x: x.row_number)
        context["steps"] = steps
        return context


class ContentDetail(LoginRequiredMixin, DetailView):
    model = Content
    template_name = "content/detail.html"
    slug_field, slug_url_kwarg = "uuid", "uuid"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"{self.get_object().title}"
        return context


@login_required
def user_watched_content(request, content_uuid):
    content = get_object_or_404(Content, uuid=content_uuid)
    WatchedContent.objects.create(user=request.user, content=content)

    if content.medals:
        request.user.received_medals = (request.user.received_medals or 0) + content.medals
        request.user.save()

    return redirect("content:roads")


class FundsManagements(LoginRequiredMixin, View):
    template_name = "content/funds-management.html"
    context = {"title":"مدیریت صندوق ها"}

    def get(self, request):
        return render(request, self.template_name, self.context)

templates/content/detail.html
{% extends "base.html" %}

{% load static %}

{% block page_css %}{% endblock page_css %}

{% block extra_menu %}{% endblock extra_menu %}

{% block main %}
<div class="row">

    <div class="col-12">
        <div class="row justify-content-center">
            <div class="col-xl-2 col-md-4 col-sm-6">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-primary p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-clock text-primary font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">{{object.get_read_time}} دقیقه</h2>
                            <p class="mb-0 line-ellipsis">مدال ها</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-2 col-md-4 col-sm-6">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-success p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-bar-chart text-success font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">مقدماتی</h2>
                            <p class="mb-0 line-ellipsis">درجه سختی</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-2 col-md-4 col-sm-6">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-warning p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-award text-warning font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">{{object.medals}}</h2>
                            <p class="mb-0 line-ellipsis">ارزش مدالی مرحله</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-7">
        <div class="card">
            <div class="card-content p-3">
                <h1 class="">اولین ویدیو آموزشی</h1>
                <p class="font-medium-1 mt-2" style="line-height: 1.6; text-align: justify;">{{object.description}}</p>

                <div class="list-inline">
                    <span class="list-inline-item my-auto">مدرس دوره: </span>
                    <div class="list-inline-item">
                        <img class="img-fluid rounded-circle" style="width: 50px; height: 50px;" src={% static "no-banner.jpg" %} alt="">
                    </div>
                    <span class="font-medium-1">اشکان هژبری</span>
                </div>
            </div>
        </div>
    </div>

    <div class="col-5">
        <div class="card">
            <div class="card-content">
                <div class="embed-responsive embed-responsive-item embed-responsive-16by9">
                    <iframe src="https://www.aparat.com/video/video/embed/videohash/{{object.get_aparat_code}}/vt/frame" allowFullScreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"></iframe>
                </div>
            </div>
        </div>
    </div>

    <div class="col-12">
        <div class="card">
            <div class="card-content p-4">
                {{object.content.html|safe}}
            </div>
        </div>
    </div>

    <div class="col-12 text-center">
        <a href={% url "content:watched-content" object.uuid %} class="btn btn-block btn-success">این آموزش را تمام کردم</a>
    </div>

</div>
{% endblock main %}

{% block page_js %}{% endblock page_js %}

templates/content/road.html
{% extends "base.html" %}

{% load static %}
{% load tag_library %}

{% block page_css %}{% endblock page_css %}

{% block main %}
<div class="row">

    {% include "elements/messages-section.html" %}

    {% if request.user.members_of_team.first and request.user.is_team_member %}
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">مراحل پیش روی شما</h4>
            </div>
            <div class="row py-2">
                {% for item in collections %}
                {% is_collection_done request.user.id item.collection.uuid as collection_done %}
                {% if not collection_done %}<span hidden>{% cycle 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 as is_first_not_done %}</span>{% endif %}
                <div class="col mx-auto p-0">
                    <div class="row text-center ml-0">
                        <div class="col-10">
                            <div class="row">
                                <div class="col-12">
                                    <div class="avatar bg-rgba-{% if collection_done %}success{% else %}{% if is_first_not_done %}primary{% else %}secondary{% endif %}{% endif %} p-50 m-0 mb-1">
                                        <div class="avatar-content" id="status-icon-{{item.collection.uuid}}-collection">
                                            {% if collection_done %}
                                            <i class="feather icon-check text-success font-medium-5"></i>
                                            {% else %}
                                                {% if is_first_not_done %}
                                                <i class="fa fa-arrow-down text-primary font-medium-5"></i>
                                                {% else %}
                                                <i class="feather icon-award text-secondary font-medium-5"></i>
                                                {% endif %}
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12"><p class="mb-0 line-ellipsis">{{item.collection.name}}</p></div>
                            </div>
                        </div>
                        {% if not forloop.last %}
                        <div class="col-2 p-0 my-auto"><i class="feather icon-chevrons-left text-secondary font-medium-5"></i></div>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="row">
            <div class="col-12">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-success p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-check-circle text-success font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">{{watched_list.count}}</h2>
                            <p class="mb-0 line-ellipsis">گذرانده شده</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-danger p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-crosshair text-danger font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">{{watched_list.count|remain_content_count:request.user}}</h2>
                            <p class="mb-0 line-ellipsis">باقی مانده</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card text-center">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="avatar bg-rgba-warning p-50 m-0 mb-1">
                                <div class="avatar-content">
                                    <i class="feather icon-award text-warning font-medium-5"></i>
                                </div>
                            </div>
                            <h2 class="text-bold-700">{{request.user.received_medals}}</h2>
                            <p class="mb-0 line-ellipsis">مدال دریافتی</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-9">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">گام های شما</h4>
            </div>
            <div class="card-content">
                <div class="card-body">
                    <p>با هرگامی که پشت سر میزاری علاوه بر آموزشی که میبینی مدال هم دریافت میکنی</p>
                    <div class="list-group">
                        {% for item in collections %}
                            {% is_collection_done request.user.id item.collection.uuid as collection_done %}
                            {% if not collection_done %}<span hidden>{% cycle 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 as is_first_not_done %}</span>{% endif %}
                            
                            {% if not collection_done and is_first_not_done %}
                                {% for content in item.collection.collection_of_content_order.all %}
                                {% if not content.content.uuid in watched_list %}<span hidden>{% cycle 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 as is_first_not_done_content %}</span>{% endif %}
                                    <a href={% url "content:detail" content.content.uuid %} class="{% if content.content.uuid in watched_list %}disabled{% endif %} list-group-item list-group-item-action rounded {% if is_first_not_done_content %}bg-success text-white{% else %}disabled{% endif %}">
                                        <div class="d-flex w-100 justify-content-between">
                                            <h5 class="mb-1 {% if is_first_not_done_content %}text-white{% endif %}">{{content.content.title}}</h5>
                                            <small class="{% if content.content.uuid in watched_list %}text-warning{% endif %} font-weight-bold">{{content.content.medals}} امتیاز <i class="feather icon-award"></i></small>
                                        </div>
                                        <p class="mb-1">{{content.content.description|truncatechars:255}}</p>
                                        <small>دسته بندی ها: {% for sub in content.content.subjects.all %}<span class="badge badge-primary mr-25">{{sub.name}}</span>{% endfor %}</small>
                                    </a>
                                {% endfor %}
                                
                                {% if item.collection.exam %}
                                {% is_exam_done request.user.id item.collection.uuid as exam_done %}
                                <a href={% url "quiz:exam-detail" item.collection.exam.uuid item.collection.uuid %} class="list-group-item list-group-item-action rounded {% if not exam_done %}bg-success text-white{% else %}disabled{% endif %}">
                                    <div class="d-flex w-100 justify-content-between">
                                        <h5 class="mb-1 {% if not exam_done %}text-white{% endif %}">{{item.collection.exam.name}}</h5>
                                        <small class="font-weight-bold">{{item.collection.exam.medals}} امتیاز <i class="feather icon-award"></i></small>
                                    </div>
                                    <span>تعداد سوال: {{item.collection.exam.questions.count}}</span>
                                </a>
                                {% endif %}

                            {% endif %}
                        {% endfor %}
                        
                        <!-- TODO: Disorganized display of the steps of the educational path (pended) -->
                        {% comment %} <hr>
                        {{steps}}
                        {% for item in steps %}
                        <hr>
                        {{item}}
                            {% if item.collection_type == 'content' %}
                            <a class="{% if item.uuid in watched_list %}disabled{% endif %} list-group-item list-group-item-action rounded {% if is_first_not_done_content %}bg-success text-white{% else %}disabled{% endif %}">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1 {% if is_first_not_done_content %}text-white{% endif %}">{{item.content.title}}</h5>
                                    <small class="{% if item.uuid in watched_list %}text-warning{% endif %} font-weight-bold">{{item.medals}} امتیاز <i class="feather icon-award"></i></small>
                                </div>
                                <p class="mb-1">{{item.description|truncatechars:255}}</p>
                                <small>دسته بندی ها: {% for sub in item.subjects.all %}<span class="badge badge-primary mr-25">{{sub.name}}</span>{% endfor %}</small>
                            </a>
                            {% endif %}
                        {% endfor %} {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="col-12">
		<div class="card bg-gradient-danger">
			<div class="card-header d-flex align-items-start pb-0">
				<div class="mx-auto">
					<h2 class="text-bold-700 mb-1 text-white">شما در هیچ تیم استارتاپی عضو نیستید!</h2>
				</div>
			</div>
		</div>
	</div>

	<div class="col-12">
		<div class="card">
			<div class="card-content">
				<div class="card-body">
					<p class="">
						<h2 class="ml-1 mb-1 font-weight-bold">چه باید کرد؟</h2>
						<ul class="list-group">
							<li class="list-group-item">۱. پیگیری از مسئول تیم خود جهت اضافه کردن شما به لیست اعضای تیم.</li>
							<li class="list-group-item">۲. ثبت تیکت برای پشتیبان وب سایت.</li>
						</ul>
					</p>
				</div>
			</div>
		</div>
	</div>
	{% endif %}

</div>
{% endblock main %}

{% block page_js %}{% endblock page_js %}