company/urls.py
from django.urls import path
from . import views

app_name = "company"

urlpatterns = [
    # # ====== Company Urls ======
    path("list/", views.CompanyList.as_view(), name="list"),
    path("<str:uuid>/profile/", views.CompanyProfile.as_view(), name="profile"),
    path("dashboard/", views.CompanyDashboard.as_view(), name="dashboard"), # Access only for company admin
    # ====== Center Urls ======
    path("center/list/", views.CenterList.as_view(), name="center-list"),
    path("center/<str:uuid>/profile/", views.CenterProfile.as_view(), name="center-profile"),
    path("accelerator/dashboard/", views.AcceleratorDashboard.as_view(), name="acc-dashboard"),
    path("accelerator/new-road/", views.CreateRoad.as_view(), name="new-road"),
    path("accelerator/<str:uuid>/update-road/", views.UpdateRoad.as_view(), name="update-road"),
    path("accelerator/<str:uuid>/delete-road/", views.DeleteRoad.as_view(), name="delete-road"),
    path("accelerator/save-collection-order/<str:road_uuid>/", views.save_collection_order, name="save-collection-order"),
    path("accelerator/delete-collection-order/<int:pk>/", views.delete_collection_order, name="delete-collection-order"),
    path("accelerator/new-collection/", views.CreateCollection.as_view(), name="new-collection"),
    path("accelerator/<str:uuid>/update-collection/", views.UpdateCollection.as_view(), name="update-collection"),
    path("accelerator/<str:uuid>/delete-collection/", views.DeleteCollection.as_view(), name="delete-collection"),
    path("accelerator/save-content-order/<str:collection_uuid>/", views.save_content_order, name="save-content-order"),
    path("accelerator/delete-content-order/<int:pk>/", views.delete_content_order, name="delete-content-order"),
    path("accelerator/new-content/", views.CreateContent.as_view(), name="new-content"),
    path("accelerator/<str:uuid>/update-content/", views.UpdateContent.as_view(), name="update-content"),
    path("accelerator/<str:uuid>/delete-content/", views.DeleteContent.as_view(), name="delete-content"),
    path("accelerator/new-exam/", views.CreateExam.as_view(), name="new-exam"),
    path("accelerator/<str:uuid>/update-exam/", views.UpdateExam.as_view(), name="update-exam"),
    path("accelerator/<str:uuid>/delete-exam/", views.DeleteExam.as_view(), name="delete-exam"),
    path("accelerator/new-question/<str:exam_uuid>/", views.new_question, name="new-question"),
    path("accelerator/<int:pk>/update-question/", views.UpdateQuestion.as_view(), name="update-question"),
    path("accelerator/delete-question/<int:pk>/", views.delete_question, name="delete-question"),
    path("accelerator/new-answer/<int:question_id>/", views.new_answer, name="new-answer"),
    path("accelerator/delete-answer/<int:pk>/", views.delete_answer, name="delete-answer"),
    path("accelerator/save-exam-order/<str:collection_uuid>/", views.save_exam_order, name="save-exam-order"),
    path("accelerator/delete-exam-order/<int:pk>/", views.delete_exam_order, name="delete-exam-order"),
    path("accelerator/new-task/", views.new_task, name="new-task"),
    path("accelerator/<str:uuid>/update-task/", views.UpdateTask.as_view(), name="update-task"),
    path("accelerator/<str:uuid>/delete-task/", views.DeleteTask.as_view(), name="delete-task"),
    path("accelerator/save-task-order/<str:collection_uuid>/", views.save_task_order, name="save-task-order"),
    path("accelerator/delete-task-order/<int:pk>/", views.delete_task_order, name="delete-task-order"),
    path("new-subject/", views.NewSubject.as_view(), name="new-subject"),
    path("team-management/", views.TeamManagement.as_view(), name="team-management"),
    path("all-requests/", views.AllRequests.as_view(), name="all-requests"),
    path("invest-management/", views.InvestManagement.as_view(), name="invest-management"),
    path("accelerator/new-register-task/", views.CreatePreRegisterTask.as_view(), name="new-register-task"),
    path("accelerator/<str:uuid>/update-register-task/", views.UpdatePreRegisterTask.as_view(), name="update-register-task"),
    path("accelerator/save_pre_register_task_question/<str:pre_register_task_uuid>/", views.save_pre_register_task_question, name="save_pre_register_task_question"),
    path("accelerator/delete_pre_register_task_question/<str:uuid>/", views.delete_pre_register_task_question, name="delete_pre_register_task_question"),

    path("accelerator/<str:uuid>/delete-register-task/", views.DeletePreRegisterTask.as_view(), name="delete-register-task"),
    path("accelerator/referee-management/", views.RefereeManagement.as_view(), name="referee-management"),

    path('logoutt/', views.create_center, name='create_center'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect, render
from django.http import Http404
from django.conf import settings
from django.contrib.auth.decorators import login_required


def router(request):
    user = request.user

    if not user.is_authenticated:
        return redirect("account:login-or-register")
    
    if user.is_superuser or user.is_staff:
        return redirect("admin:index")
    elif user.is_team_member and user.user_of_road_registration.first():
        registration_obj = user.user_of_road_registration.first()
        if registration_obj.status != "n":
            return redirect("content:roads")
        if int(registration_obj.status_user_state) == 2:
            return redirect("account:register2")
        elif int(registration_obj.status_user_state) == 3:
            return redirect("account:register3")
        elif int(registration_obj.status_user_state) == 4:
            return redirect("account:register4")
        elif int(registration_obj.status_user_state) == 5:
            return redirect("account:user-dashboard")
        return redirect("content:roads")
    elif user.is_center_staff():
        return redirect("company:acc-dashboard")
    elif user.is_referee:
        return redirect("account:referee-dashboard")
    elif user.is_mentor:
        return redirect("account:mentor-dashboard")
    elif user.is_investor:
        return redirect("investor:dashboard")
    elif user.is_company:
        return redirect("company:dashboard")
    else:
        raise Http404("You do not have valid permissions!")


@login_required
def under_maintenance(request):
    return render(request, "under_maintenance.html", {})


@login_required
def forbidden(request, *args, **kwargs):
    return render(request, "forbidden.html", {})


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", router, name="router"),
    path("under-maintenance", under_maintenance, name="under-maintenance"),
    path('accounts/', include('account.urls')),
    path('content/', include('content.urls')),
    path('company/', include('company.urls')),
    path('quiz/', include('quiz.urls')),
    path('plan/', include('plan.urls')),
    path('team/', include('team.urls')),
    path('investor/', include('investor.urls')),
    path('assessment/', include('assessment.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/urls.py
from django.urls import path
from . import views
from config.urls import forbidden

app_name = "plan"
urlpatterns = [
    path("create/", views.CreatePlan.as_view(), name="create"),
    path("<str:uuid>/profile/", views.TeamProductProfile.as_view(), name="profile"),
    path("<str:uuid>/detail/", views.PlanDetail.as_view(), name="detail"),
]

quiz/models.py
from django.db import models
from utils.uuid_generator import random_uuid4
from django_quill.fields import QuillField


class Answer(models.Model):
    text = models.CharField(max_length=128, verbose_name="متن")
    is_valid = models.BooleanField(default=False, verbose_name="درست بودن")
    accelerator = models.ForeignKey("company.Center", related_name="accelerator_of_answer", verbose_name="برگزارکننده", null=True, on_delete=models.CASCADE)

    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "جواب"
        verbose_name_plural = "جواب ها"

    def __str__(self) -> str:
        return f"{self.text} : {self.is_valid}"


class Question(models.Model):
    text = models.CharField(max_length=256, verbose_name="متن")
    answers = models.ManyToManyField(Answer, verbose_name="گزینه ها", blank=True)
    accelerator = models.ForeignKey("company.Center", related_name="accelerator_of_question", verbose_name="برگزارکننده", null=True, on_delete=models.CASCADE)

    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "سوآل"
        verbose_name_plural = "سوآل ها"

    def __str__(self) -> str:
        return self.text


class Exam(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    name = models.CharField(max_length=64, verbose_name="عنوان")
    questions = models.ManyToManyField(Question, verbose_name="سوال ها", blank=True)
    medals = models.PositiveIntegerField(verbose_name="مدال", default=0)
    accelerator = models.ForeignKey("company.Center", related_name="accelerator_of_exam", verbose_name="برگزارکننده", null=True, on_delete=models.CASCADE)

    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "آزمون"
        verbose_name_plural = "آزمون ها"

    def __str__(self) -> str:
        return self.name


class UserExamAnsewrHistory(models.Model):
    user = models.ForeignKey("account.user", related_name="ansewr_history_of_user", on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, related_name="ansewr_history_of_exam", on_delete=models.CASCADE)
    question = models.ForeignKey(Question, related_name="ansewr_history_of_question", on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, related_name="ansewr_history_of_answer", on_delete=models.CASCADE)

    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "پاسخ ها کاربر"
        verbose_name_plural = "پاسخ های کاربر "

    def __str__(self):
        return f"{self.user} - {self.exam} - {self.question} - {self.answer}"


class ExamOrder(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )

    collection = models.ForeignKey("content.collection", verbose_name="فصل", on_delete=models.CASCADE, related_name="collection_of_exam_order", null=True)
    exam = models.ForeignKey(Exam, verbose_name="آزمون", on_delete=models.CASCADE, related_name="road_of_exam_order", null=True)
    row_number = models.PositiveIntegerField(verbose_name="شماره ردیف")

    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "ترتیب آزمون"
        verbose_name_plural = "ترتیب آزمون ها"

    def __str__(self) -> str:
        return f"{self.collection} - {self.exam} - {self.row_number}"
    
    
class Task(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    title = models.CharField(max_length=64, verbose_name="عنوان")
    text = QuillField(default="", verbose_name="محتوا متنی")
    medals = models.PositiveIntegerField(verbose_name="مدال", default=0)
    accelerator = models.ForeignKey("company.Center", related_name="accelerator_of_task", verbose_name="برگزارکننده", null=True, on_delete=models.CASCADE)

    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "تسک"
        verbose_name_plural = "تسک ها"

    def __str__(self) -> str:
        return self.title


class TaskOrder(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    
    collection = models.ForeignKey("content.collection", verbose_name="فصل", on_delete=models.CASCADE, related_name="collection_of_task_order", null=True)
    task = models.ForeignKey(Task, verbose_name="تسک", on_delete=models.CASCADE, related_name="road_of_task_order", null=True)
    row_number = models.PositiveIntegerField(verbose_name="شماره ردیف")

    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "ترتیب تسک"
        verbose_name_plural = "ترتیب تسک ها"

    def __str__(self) -> str:
        return f"{self.collection.name} : {self.task.title} - {self.row_number}"


class TaskResponse(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    user = models.ForeignKey("account.User", verbose_name="کاربر", related_name="user_of_task_response", on_delete=models.CASCADE)
    task = models.ForeignKey(Task, verbose_name="تسک", related_name="task_of_task_response", on_delete=models.CASCADE)
    file = models.FileField(verbose_name="فایل", upload_to="task-response/%Y/%m/", max_length=100)
    title = models.CharField(max_length=64, verbose_name="عنوان")
    text = QuillField(default="", verbose_name="محتوا متنی")
    
    STATUS = (
        ("w", "در انتظار برسی"), # Waiting
        ("d", "تایید شده"), # Done
        ("r", "رد شده"), # Reject
    )
    status = models.CharField(choices=STATUS, max_length=1, default="w", verbose_name="وضعیت")

    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "پاسخ تسک"
        verbose_name_plural = "پاسخ تسک ها"

    def __str__(self) -> str:
        return self.title




# PreRegisterTask = Challenge: an object of this model can be for a tech or business guy
class PreRegisterTask(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    title = models.CharField(max_length=64, verbose_name="عنوان")
    TYPES = (
        ("t", "تکنولوژی"), # Tech
        ("b", "کسب‌وکار"), # Business
    )
    type = models.CharField(choices=TYPES, max_length=1, default="t", verbose_name="نوع")

    accelerator = models.ForeignKey("company.Center", related_name="accelerator_of_pre_register_task", verbose_name="برگزارکننده", null=True, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "آزمون پیش ثبت نام"
        verbose_name_plural = "آزمون های پیش ثبت نام"

    def __str__(self) -> str:
        return f"{self.title} ({self.get_type_display()})"
    

class PreRegisterTaskQuestion(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    pre_register = models.ForeignKey(PreRegisterTask, verbose_name="آزمون", on_delete=models.CASCADE, related_name="pre_register_of_pre_register_task_question",)

    title = models.CharField(max_length=255, verbose_name="عنوان")
    text = QuillField(verbose_name="متن سوال")

    aparat_embed_code = models.CharField(verbose_name="لینک embed آپارات", max_length=255, null=True, blank=True)

    accelerator = models.ForeignKey("company.Center", related_name="accelerator_of_pre_register_task_question", verbose_name="برگزارکننده", null=True, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True, null=True, verbose_name="زمان ساخت")
    last_update_time = models.DateTimeField(auto_now=True, null=True, verbose_name="زمان بروزرسانی")

    class Meta:
        verbose_name = "سوال های آزمون پیش ثبت نام"
        verbose_name_plural = "سوال های آزمون های پیش ثبت نام"

    def __str__(self) -> str:
        return f"{self.pre_register}"


class PreRegisterTaskResponse(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    # The user who answered to pre register task
    user = models.ForeignKey("account.User", verbose_name="کاربر", related_name="user_of_pre_register_task_response", on_delete=models.CASCADE)
    # The task that user answered

templates/company/center/accelerator/update-collection.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load tag_library %}

{% block page_css %}
<link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/vendors/css/tables/datatable/datatables.min.css" %}>

<link href={% static "assets-vuexy/vendor/libs/select2/select2.css" %} rel="stylesheet"/>
{% endblock page_css %}

{% block extra_menu %}{% endblock extra_menu %}

{% block main %}
<div class="row">

    {% include "elements/messages-section.html" %}


    <div class="col-lg-8">
        <div class="card">
            <h5 class="card-header"><i class="fa fa-hashtag text-black-50"></i> مدیریت گام های فصل</h5>
            <div class="card-body">

                <div id="div_id_type" class="form-group">
                    <label for="id_type" class=" requiredField">
                        آزمون یا گام؟
                    </label>
                    <div>
                        <select name="type" class="select form-control" required="" id="id_type">
                            <option value="c">گام</option>
                            <option value="e">آزمون</option>
                            <option value="t">تسک</option>
                        </select>
                    </div>
                </div>

                <form method="POST" action={% url "company:save-content-order" object.uuid %} id="content_order_form">
                    {% csrf_token %}
                    <div class="row">
                        {% for field in content_order_form %}
                            {% if not field.name == "collection" %}
                            <div class="col-md-6 mt-3">
                                {{ field|as_crispy_field }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <button class="btn btn-label-success mt-3" type="submit">قراردهی گام</button>
                </form>

                <form method="POST" action={% url "company:save-exam-order" object.uuid %} id="exam_order_form" style="display: none;">
                    {% csrf_token %}
                    <div class="row">
                        {% for field in exam_order_form %}
                            {% if not field.name == "collection" %}
                            <div class="col-md-6 mt-3">
                                {{ field|as_crispy_field }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <button class="btn btn-label-success mt-3" type="submit">قراردهی آزمون</button>
                </form>

                <form method="POST" action={% url "company:save-task-order" object.uuid %} id="task_order_form" style="display: none;">
                    {% csrf_token %}
                    <div class="row">
                        {% for field in task_order_form %}
                            {% if not field.name == "collection" %}
                            <div class="col-md-6 mt-3">
                                {{ field|as_crispy_field }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>

                    <button class="btn btn-label-success mt-3" type="submit">قراردهی تسک</button>
                </form>

                <div class="row mt-4">

                    <div class="col-12">
                        <div class="card">
                            <h5 class="card-header"><i class="fa fa-hashtag text-black-50"></i> ترتیب قرارگیری گام های این فصل</h5>
                            <div class="card-content">
                                <div class="card-body card-dashboard p-0">
                                    <div class="table-responsive">
                                        <table class="table zero-configuration">
                                            <thead>
                                                <tr class="table-warning">
                                                    <th>#</th>
                                                    <th>نوع</th>
                                                    <th>عنوان</th>
                                                    <th>عملیات</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for order in object.collection_of_content_order.all %}
                                                    <tr>
                                                        <th scope="row">{{order.row_number|default:"0"|stringformat:"02d"}}</th>
                                                        <td><span class="badge badge-primary">گام</span></td>
                                                        <td class="font-weight-bold"><a href={% url "company:update-content" order.content.uuid %} class="">{{order.content.title|truncatechars:25}}</a></td>
                                                        <td><a href={% url "company:delete-content-order" order.id %} class="badge badge-danger">حذف</a></td>
                                                    </tr>
                                                {% endfor %}
                                                {% for order in object.collection_of_exam_order.all %}
                                                    <tr>
                                                        <th scope="row">{{order.row_number|default:"0"|stringformat:"02d"}}</th>
                                                        <td><span class="badge badge-warning">آزمون</span></td>
                                                        <td class="font-weight-bold"><a href={% url "company:update-exam" order.exam.uuid %} class="">{{order.exam.name|truncatechars:20}}</a></td>
                                                        <td><a href={% url "company:delete-exam-order" order.id %} class="badge badge-danger">حذف</a></td>
                                                    </tr>
                                                {% endfor %}
                                                {% for order in object.collection_of_task_order.all %}
                                                    <tr>
                                                        <th scope="row">{{order.row_number|default:"0"|stringformat:"02d"}}</th>
                                                        <td><span class="badge badge-info">تسک</span></td>
                                                        <td class="font-weight-bold"><a href={% url "company:update-task" order.task.uuid %} class="">{{order.task.title|truncatechars:20}}</a></td>
                                                        <td><a href={% url "company:delete-task-order" order.id %} class="badge badge-danger">حذف</a></td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


    <div class="col-lg-4">
        <div class="card">
            <h5 class="card-header"><i class="fa fa-hashtag text-black-50"></i> فصل «{{object.name}}»</h5>
            <div class="card-content">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <input name="accelerator" value="{{acc_object.id}}" hidden>
                        <div class="row">
                            {% for field in form %}
                                {% if not field.name == "accelerator" %}
                                <div class="col-12">
                                    {{ field|as_crispy_field }}
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>

                        <button class="btn btn-label-success mt-3" type="submit">ویراش فصل</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock main %}

{% block page_js %}
<script src={% static "admin-theme/app-assets/vendors/js/tables/datatable/datatables.min.js" %}></script>
<script src={% static "admin-theme/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js" %}></script>
<script src={% static "admin-theme/app-assets/js/scripts/datatables/datatable.js" %}></script>

<script src={% static "assets-vuexy/vendor/libs/select2/select2.js" %}></script>
<script src={% static "assets-vuexy/js/forms-selects.js" %}></script>

<script>
    // Get the select element
    const selectElement = document.getElementById('id_type');
    
    // Get the elements to show/hide
    const contentOrderForm = document.getElementById('content_order_form');
    const examOrderForm = document.getElementById('exam_order_form');
    const taskOrderForm = document.getElementById('task_order_form');
    
    // Add event listener for 'change' event
    selectElement.addEventListener('change', function() {
        // Get the selected value
        const selectedValue = this.value;
        
        // Check the selected value and hide/show elements accordingly
        if (selectedValue === 'c') {
            contentOrderForm.style.display = 'block';
            examOrderForm.style.display = 'none';
            taskOrderForm.style.display = 'none';
        } else if (selectedValue === 'e') {
            examOrderForm.style.display = 'block';
            contentOrderForm.style.display = 'none';
            taskOrderForm.style.display = 'none';
        } else if (selectedValue === 't') {
            taskOrderForm.style.display = 'block';
            contentOrderForm.style.display = 'none';
            examOrderForm.style.display = 'none';
        }
    });
</script>
{% endblock page_js %}

templates/company/center/accelerator/update-question.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load tag_library %}

{% block page_css %}{% endblock page_css %}

{% block extra_menu %}{% endblock extra_menu %}

{% block main %}
<div class="row">

    {% include "elements/messages-section.html" %}

    <div class="col-md-8">
        <div class="card">
            <h5 class="card-header pb-1">گزینه های ساخته شده</h5>
            <div class="card-content">
                <div class="card-body">
                    <table class="table table-responsive-md mb-0">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">نام گزینه</th>
                                <th scope="col">درست بودن</th>
                                <th scope="col">عملیات</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for answer in object.answers.all %}
                                <tr>
                                    <th scope="row">{{forloop.counter|stringformat:"02d"}}</th>
                                    <td class="font-weight-bold">{{answer.text}}</td>
                                    <td><i class="feather text-{{answer.is_valid|yesno:"success,danger"}} icon-{{answer.is_valid|yesno:"check,x"}}-circle"></i></td>
                                    <td><a href={% url "company:delete-answer" answer.id %} class="badge bg-label-danger">حذف</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    
                    <h5 class="mt-4">فرم ساخت گزینه</h5>
                    <form method="POST" action={% url "company:new-answer" object.id %}>
                        {% csrf_token %}
                        <input name="accelerator" value="{{acc_object.id}}" hidden>
                        {% for field in answer_form %}
                            {% if not field.name == "accelerator" %}
                            <div class="col-12 mt-2">
                                {{ field|as_crispy_field }}
                            </div>
                            {% endif %}
                        {% endfor %}
                        <button class="btn btn-label-success mt-3" type="submit">ثبت گزینه</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>

    <div class="col-4">
        <div class="card">
            <h5 class="card-header pb-1">ویرایش «{{object.text}}»</h5>
            <div class="card-content">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <input name="accelerator" value="{{acc_object.id}}" hidden>
                        <div class="row">
                            {% for field in form %}
                                {% if not field.name == "accelerator" %}
                                <div class="col-12 mt-3">
                                    {{ field|as_crispy_field }}
                                </div>
                                {% endif %}
                            {% endfor %}
                        </div>

                        <button class="btn btn-label-success mt-3" type="submit">ویراش سوال</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock main %}

{% block page_js %}{% endblock page_js %}