config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect, render
from django.http import Http404
from django.conf import settings
from django.contrib.auth.decorators import login_required


def router(request):
    user = request.user

    if not user.is_authenticated:
        return redirect("account:login-or-register")
    
    if user.is_superuser or user.is_staff:
        return redirect("admin:index")
    elif user.is_team_member and user.user_of_road_registration.first():
        registration_obj = user.user_of_road_registration.first()
        if registration_obj.status != "n":
            return redirect("content:roads")
        if int(registration_obj.status_user_state) == 2:
            return redirect("account:register2")
        elif int(registration_obj.status_user_state) == 3:
            return redirect("account:register3")
        elif int(registration_obj.status_user_state) == 4:
            return redirect("account:register4")
        elif int(registration_obj.status_user_state) == 5:
            return redirect("account:user-dashboard")
        return redirect("content:roads")
    elif user.is_center_staff():
        return redirect("company:acc-dashboard")
    elif user.is_referee:
        return redirect("account:referee-dashboard")
    elif user.is_mentor:
        return redirect("account:mentor-dashboard")
    elif user.is_investor:
        return redirect("investor:dashboard")
    elif user.is_company:
        return redirect("company:dashboard")
    else:
        raise Http404("You do not have valid permissions!")


@login_required
def under_maintenance(request):
    return render(request, "under_maintenance.html", {})


@login_required
def forbidden(request, *args, **kwargs):
    return render(request, "forbidden.html", {})


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", router, name="router"),
    path("under-maintenance", under_maintenance, name="under-maintenance"),
    path('accounts/', include('account.urls')),
    path('content/', include('content.urls')),
    path('company/', include('company.urls')),
    path('quiz/', include('quiz.urls')),
    path('plan/', include('plan.urls')),
    path('team/', include('team.urls')),
    path('investor/', include('investor.urls')),
    path('assessment/', include('assessment.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investor/urls.py
from django.urls import path
from . import views

app_name = "investor"
urlpatterns = [
    path("dashboard/", views.InvestorDashboard.as_view(), name="dashboard"),
    path("funds/management/", views.FundsManagements.as_view(), name="funds-management"),
    path("funds/<str:uuid>/update/", views.UpdateFund.as_view(), name="update-fund"),
    path("funds/<str:uuid>/delete/", views.delete_fund, name="delete-fund"),
    path("roads/list/", views.RoadList.as_view(), name="roads"),
    path("roads/<str:uuid>/investment/", views.RoadInvestment.as_view(), name="road-investment"),
    path("products/list/", views.ProductList.as_view(), name="product-list"),
    path("products/<str:uuid>/investment/", views.ProductInvestment.as_view(), name="product-investment"),
]

plan/urls.py
from django.urls import path
from . import views
from config.urls import forbidden

app_name = "plan"
urlpatterns = [
    path("create/", views.CreatePlan.as_view(), name="create"),
    path("<str:uuid>/profile/", views.TeamProductProfile.as_view(), name="profile"),
    path("<str:uuid>/detail/", views.PlanDetail.as_view(), name="detail"),
]

team/urls.py
from django.urls import path
from . import views

app_name = "team"
urlpatterns = [
    path("", views.TeamDashboard.as_view(), name="dashboard"),
    path("<str:uuid>/profile/", views.TeamProfile.as_view(), name="profile"),
    path("manage-teams/", views.CreateTeam.as_view(), name="manage-teams"),
    path("<str:uuid>/update-team/", views.UpdateTeam.as_view(), name="update-team"),
    path("save-team-member/", views.save_team_member, name="save-team-member"),
    path("<str:uuid>/<str:team_uuid>/delete-team-member/", views.delete_team_member, name="delete-team-member"),
    path("road-registration/<str:uuid>/", views.RoadRegistrationView.as_view(), name="road-registration"),
    path("registration/detail/<str:uuid>/", views.RegistrationDetail.as_view(), name="registration-detail"),
    path("reject_registration/<str:uuid>/", views.reject_registration, name="reject_registration"),
    path("approve_registration/<str:uuid>/", views.approve_registration, name="approve_registration"),
    path("funds/management/", views.FundsManagements.as_view(), name="funds-management"),
    path("idea/management/", views.IdeaManagements.as_view(), name="idea-management"),
    path("product/management/", views.ProductManagements.as_view(), name="product-management"),
    path("save/product/", views.save_product, name="save-product"),
    path("save-extra-day-for-complete-registration/", views.save_extra_day_for_complete_registration, name="save-extra-day-for-complete-registration"),
    path("product/<str:user_uuid>/profile/", views.PlanAndTeamProfile.as_view(), name="plan-team-profile"),
    path("add/product/", views.AddProduct.as_view(), name="add-product"),
    path("searchZi/", views.searchzi, name="searchZi"),
    path("search/", views.search_iframe, name="search-iframe"),

    path('logoutt/', views.create_team, name='create_center'),
]

investor/models.py
from django.core.exceptions import ValidationError
from django.db import models
from utils.uuid_generator import random_uuid4
from account.models import User

def validate_is_investor(value):
    value = User.objects.get(id=value)
    if not value.is_investor:
        raise ValidationError('کاربر انتخابی باید درسترسی سرمایه گذار را داشته باشد.')


class InvestorFound(models.Model):
    uuid = models.CharField(
        unique=True,
        max_length=36,
        blank=True,
        default=random_uuid4,
        editable=False,
    )
    investor = models.ForeignKey("account.User", verbose_name="سرمایه گذار", on_delete=models.CASCADE, validators=[validate_is_investor], related_name="fund_of_investor")
    name = models.CharField(verbose_name="نام صندوق", max_length=255)
    amount = models.PositiveIntegerField(default=0, verbose_name="حجم صندوق")

    created_time = models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد", null=True)
    last_update_time = models.DateTimeField(auto_now=True, verbose_name="زمان آخرین بروزرسانی", null=True)

    class Meta:
        verbose_name = "صندوق"
        verbose_name_plural = "صندوق ها"

    def __str__(self) -> str:
        return self.name

investor/forms.py
from django.forms import ModelForm

from .models import InvestorFound


class InvestorFoundCreationForm(ModelForm):
    class Meta:
        model = InvestorFound
        exclude = ("created_time", "last_update_time", "uuid")


class InvestorFoundUpdateForm(ModelForm):
    class Meta:
        model = InvestorFound
        exclude = ("created_time", "last_update_time", "uuid", "investor")

investor/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import View, UpdateView, ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from content.models import Road
from plan.models import Plan

from .forms import  InvestorFoundCreationForm, InvestorFoundUpdateForm
from .models import InvestorFound


class InvestorDashboard(LoginRequiredMixin, View):
    template_name = "investor/dashboard.html"
    context = {"title":"داشبورد سرمایه گذار"}

    def get(self, request):
        return render(request, self.template_name, self.context)


class FundsManagements(LoginRequiredMixin, View):
    template_name = "investor/funds-management.html"
    form_class = InvestorFoundCreationForm
    context = {"title":"مدیریت صندوق ها"}

    def get(self, request):
        self.context["fund_form"] = self.form_class
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        if request.method == 'POST':
            form = self.form_class(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "عملیات با موفقیت انجام شد")
            else:
                messages.error(request, "مشکلی در فرم وجود دارد!")
        else:
            messages.error(request, "درخاست نامعتبر!")
        return redirect(reverse('investor:funds-management'))


class UpdateFund(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = InvestorFound
    template_name = "investor/update-fund.html"
    form_class = InvestorFoundUpdateForm
    success_message = "عملیات با موفقیت انجام شد"
    slug_field, slug_url_kwarg = "uuid", "uuid"

    def get_success_url(self, **kwargs):         
        return reverse_lazy('investor:update-fund', args = (self.object.uuid,))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "ویرایش صندوق"
        return context
    

@login_required
def delete_fund(request, uuid):
    try:
        InvestorFound.objects.get(uuid=uuid).delete()
        messages.success(request, "عملیات با موفقیت انجام شد")
    except:
        messages.error(request, "درخاست نامعتبر!")

    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class RoadList(LoginRequiredMixin, ListView):
    model = Road
    template_name = "investor/roads.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "لیست برنامه های فعال"
        return context


class RoadInvestment(LoginRequiredMixin, View):
    template_name = "investor/road-investment.html"
    context = {"title": "سرمایه گذاری برروی برنامه"}

    def get(self, request, uuid):
        obj = Road.objects.get(uuid=uuid)
        self.context["object"] = obj
        return render(request, self.template_name, self.context)


class ProductList(LoginRequiredMixin, ListView):
    model = Plan
    template_name = "investor/product-list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "لیست برنامه های فعال"
        return context


class ProductInvestment(LoginRequiredMixin, View):
    template_name = "investor/product-investment.html"
    context = {"title": "سرمایه گذاری برروی محصول"}

    def get(self, request, uuid):
        obj = Plan.objects.get(uuid=uuid)
        self.context["object"] = obj
        return render(request, self.template_name, self.context)

templates/investor/product-investment.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load tag_library %}

{% block page_css %}
<link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/vendors/css/forms/select/select2.min.css" %}>
<link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/css-rtl/pages/faq.css" %}>
{% endblock page_css %}

{% block main %}
<div class="row">

    {% include "elements/messages-section.html" %}

    <div class="col-12 card">
        <div class="row">
            <div class="col-12">
                <h1 class="my-3 font-weight-bold font-large-2 text-center">{{object.name}}</h1>
            </div>
            <div class="col-12 text-center">
                <img src="{% if object.poster %}{{object.poster.url}}{% else %}{% static "no-banner.jpg" %}{% endif %}" alt="{{object.name}}" class="img-fluid">
            </div>
        </div>
    </div>


    <div class="col-12">
        <div class="row">
            <div class="col-lg-12">
                <!-- Detail and registration button -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">اختصاص دهی اعتبار به این محصول</h4>
                    </div>
                    <div class="card-body">
                        <div class="card-content">
                            <table class="table table-responsive-md mb-0 text-dark">
                                <thead>
                                    <tr class="table-light">
                                        <th scope="col">توضیحات</th>
                                        <th scope="col">میانگین بلوغ محصول</th>
                                        <th scope="col">اعتبار اختصاص داده شما</th>
                                        <th scope="col">میزان سهام شما</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="font-weight-bold col-6">{{object.description}}</td>
                                        <td class="">سطح سوم</td>
                                        <td class="">0</td>
                                        <td class="">0 درصد</td>
                                    </tr>
                                </tbody>
                            </table>

                            <form method="post" class="mt-2" action={% url "team:road-registration" object.uuid %}>
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    <label for="id_amount" class="requiredField">حجم اعتبار<span class="asteriskField">*</span></label>
                                    <input type="number" name="amount" value="0" min="0" max="100" class="numberinput form-control" required="" id="id_amount">
                                </fieldset>
                                <button type="submit" class="btn btn-block btn-gradient-bg bg-gradient-success">ثبت اعتبار</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- FAQ -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"><i class="fa fa-question-circle"></i> سوالات متداول</h4>
                    </div>
                    <div class="card-body">
                        <div class="card-content">
                            <div class="accordion search-content-info" id="accordionExample">
                                <div class="collapse-margin search-content mt-0">
                                    <div class="card-header" id="headingOne" role="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        <span class="lead collapse-title">تفاوت اختصاص اعتبار و سرمایه گذاری در جیست؟</span>
                                    </div>
                                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                                        <div class="card-body">
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                        </div>
                                    </div>
                                </div>
                                <div class="collapse-margin">
                                    <div class="card-header" id="headingTwo" role="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        <span class="lead collapse-title collapsed">
                                            گزارش های پیشرفت و وضعیت سرمایه من به شکل به من نمایش داده میشود؟
                                        </span>
                                    </div>
                                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                                        <div class="card-body">
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock main %}

{% block page_js %}
<script src={% static "admin-theme/app-assets/vendors/js/forms/select/select2.full.min.js" %}></script>
<script src={% static "admin-theme/app-assets/js/scripts/forms/select/form-select2.js" %}></script>
<script src={% static "admin-theme/app-assets/js/scripts/pages/faq-kb.js" %}></script>
{% endblock page_js %}

templates/investor/product-list.html
{% extends "base.html" %}

{% load static %}
{% load tag_library %}

{% block page_css %}
<link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/vendors/css/tables/datatable/datatables.min.css" %}>
{% endblock page_css %}

{% block extra_menu %}{% endblock extra_menu %}

{% block main %}
<div class="row">
    <div class="col-12">
        <section id="basic-datatable">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">لیست محصولات تیم ها</h4>
                        </div>
                        <div class="card-content">
                            <div class="card-body card-dashboard">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr class="table-primary">
                                                <th>عنوان</th>
                                                <th>توضیحات</th>
                                                <th>سطح بلوغ</th>
                                                <th>تیم</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for object in object_list %}
                                            <tr>
                                                <td class="font-weight-bold text-primary"><img class="img-fluid img-thumbnail" width="50" src="{% if item.logo %}{{item.logo.url}}{% else %}{% static "no-banner.jpg" %}{% endif %}" alt="لوگو {{object.name}}"><a href={% url "investor:product-investment" object.uuid %} class="ml-1">{{object.name}}</a></td>
                                                <td>{{object.description|truncatechars:255}}</td>
                                                <td>سطح {{forloop.counter|add:1}}</td>
                                                <td>{{object.team.name}}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ Zero configuration table -->
    </div>
</div>
{% endblock main %}

{% block page_js %}
    <script src={% static "admin-theme/app-assets/vendors/js/tables/datatable/datatables.min.js" %}></script>
    <script src={% static "admin-theme/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js" %}></script>
    <script src={% static "admin-theme/app-assets/js/scripts/datatables/datatable.js" %}></script>
{% endblock page_js %}

templates/investor/road-investment.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load tag_library %}

{% block page_css %}
<link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/vendors/css/forms/select/select2.min.css" %}>
<link rel="stylesheet" type="text/css" href={% static "admin-theme/app-assets/css-rtl/pages/faq.css" %}>
{% endblock page_css %}

{% block main %}
<div class="row">

    {% include "elements/messages-section.html" %}

    <div class="col-12 card">
        <div class="row">
            <div class="col-lg-8 p-0">
                <img src="{% if object.poster %}{{object.poster.url}}{% else %}{% static "no-banner.jpg" %}{% endif %}" alt="{{object.name}}" class="img-fluid">
            </div>
            <div class="col-lg-4">
                <div class="h-100 p-2">
                    <h2 class="mt-3 mr-3 font-weight-bold">{{object.name}}</h2>
                    <li class="list-group mt-2">
                        <i class="text-black-50 mt-50"><i class="feather icon-tag"></i> هزینه: <span class="{% if object.price <= 0 %}text-warning{% endif %}">{{object.price|not_zero}}</span></i>
                        <i class="text-black-50 mt-50"><i class="feather icon-map-pin"></i> محل برگزاری: {{object.location}}</i>
                        <i class="text-black-50 mt-50">برگزار کننده: <img src={% if object.accelerator.logo %}{{object.accelerator.logo.url}}{% else %}{% static "no-banner.jpg" %}{% endif %} alt={{object.accelerator.name}} class="img-thumbnail" width="100"></i>
                    </li>
                </div>
            </div>
        </div>
    </div>


    <div class="col-12">
        <div class="row">
            <div class="col-lg-8">
                <!-- Detail and registration button -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">اختصاصی دهی اعتبار به این برنامه</h4>
                    </div>
                    <div class="card-body">
                        <div class="card-content">
                            <table class="table table-responsive-md mb-0 text-dark">
                                <thead>
                                    <tr class="table-light">
                                        <th scope="col">توضیحات</th>
                                        <th scope="col">تعداد تیم ها</th>
                                        <th scope="col">تعداد محصولات</th>
                                        <th scope="col">میانگین بلوغ محصولات</th>
                                        <th scope="col">اعتبار اختصاص داده شما</th>
                                        <th scope="col">میزان سهام شما</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="font-weight-bold col-6">{{object.description}}</td>
                                        <td class="">{{object.road_of_road_registration.count}} <span class="text-black-50">تیم</span></td>
                                        <td class="">{{object.road_of_road_registration.count|add:1}} <span class="text-black-50">محصول</span></td>
                                        <td class="">سطح سوم</td>
                                        <td class="">0</td>
                                        <td class="">0 درصد</td>
                                    </tr>
                                </tbody>
                            </table>

                            <form method="post" class="mt-2" action={% url "team:road-registration" object.uuid %}>
                                {% csrf_token %}
                                <fieldset class="form-group">
                                    <label for="id_amount" class="requiredField">حجم اعتبار<span class="asteriskField">*</span></label>
                                    <input type="number" name="amount" value="0" min="0" max="100" class="numberinput form-control" required="" id="id_amount">
                                </fieldset>
                                <button type="submit" class="btn btn-block btn-gradient-bg bg-gradient-success">ثبت اعتبار</button>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- FAQ -->
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title"><i class="fa fa-question-circle"></i> سوالات متداول</h4>
                    </div>
                    <div class="card-body">
                        <div class="card-content">
                            <div class="accordion search-content-info" id="accordionExample">
                                <div class="collapse-margin search-content mt-0">
                                    <div class="card-header" id="headingOne" role="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                        <span class="lead collapse-title">تفاوت اختصاص اعتبار و سرمایه گذاری در جیست؟</span>
                                    </div>
                                    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                                        <div class="card-body">
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                        </div>
                                    </div>
                                </div>
                                <div class="collapse-margin">
                                    <div class="card-header" id="headingTwo" role="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                        <span class="lead collapse-title collapsed">
                                            گزارش های پیشرفت و وضعیت سرمایه من به شکل به من نمایش داده میشود؟
                                        </span>
                                    </div>
                                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                                        <div class="card-body">
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                            لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است.
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock main %}

{% block page_js %}
<script src={% static "admin-theme/app-assets/vendors/js/forms/select/select2.full.min.js" %}></script>
<script src={% static "admin-theme/app-assets/js/scripts/forms/select/form-select2.js" %}></script>
<script src={% static "admin-theme/app-assets/js/scripts/pages/faq-kb.js" %}></script>
{% endblock page_js %}

templates/investor/road-list.html
{% extends "base.html" %}

{% load static %}
{% load tag_library %}

{% block page_css %}{% endblock page_css %}

{% block main %}
<div class="row">

    {% include "elements/messages-section.html" %}

    <div class="col-12">
        <div class="row">
            {% for item in object_list %}
            <div class="col-md-3">
                <div class="card">
                    <div class="card-content">
                        <img class="card-img-top img-fluid" src="{% if item.poster %}{{item.poster.url}}{% else %}{% static "no-banner.jpg" %}{% endif %}" alt="{{item.name}}" />
                        <div class="card-body">
                            <h4 class="card-title"><a href={% url "investor:road-investment" item.uuid %} class="font-weight-bold">{{item.name}}</a></h4>
                            <p class="card-text">{{item.description|default:"بدون توضیحات*"}}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock main %}

{% block page_js %}{% endblock page_js %}

templates/investor/update-fund.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% load tag_library %}

{% block page_css %}{% endblock page_css %}

{% block main %}
<div class="row">

	{% include "elements/messages-section.html" %}

    <div class="col-12">
        <div class="row">
            <div class="col-sm-12">
                <div class="card overflow-hidden">
                    <div class="card-content">
                        <div class="card-body">

                            <form method="POST">
                                {% csrf_token %}
                                <div class="row">
                                    {% for field in form %}
                                        {% if not field.name == "investor" %}
                                        <div class="col-6">
                                            {{field|as_crispy_field}}
                                        </div>
                                        {% endif %}
                                    {% endfor %}

                                    <div class="col-12">
                                        <button class="btn btn-success btn-block" type="submit">ثبت</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock main %}

{% block page_js %}{% endblock page_js %}